
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuroFactor.Models.dao
{

using System;
    using System.Collections.Generic;
    
public partial class operacion
{

    public int idOperacion { get; set; }

    public string Tipo { get; set; }

    public System.DateTime Fecha { get; set; }

    public int idDeuda { get; set; }



    public virtual deuda deuda { get; set; }

}

}
