
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuroFactor.Models.dao
{

using System;
    using System.Collections.Generic;
    
public partial class plancontratado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public plancontratado()
    {

        this.consulta = new HashSet<consulta>();

    }


    public int idPlanContratado { get; set; }

    public int PlanConsulta_idPlanConsulta { get; set; }

    public int Financiera_idFinanciera { get; set; }

    public System.DateTime FechaContrato { get; set; }

    public bool Activo { get; set; }

    public string ContrasenaWS { get; set; }

    public string UsuarioWS { get; set; }

    public string Serial { get; set; }

    public string SalWS { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<consulta> consulta { get; set; }

    public virtual financiera financiera { get; set; }

    public virtual planconsulta planconsulta { get; set; }

}

}
