//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroFactorWS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class deuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deuda()
        {
            this.operacion = new HashSet<operacion>();
        }
    
        public int idDeuda { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public decimal MontoFinanciado { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string FolioDocumento { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal MontoNominal { get; set; }
        public int Divisa_idDivisa { get; set; }
        public int idEmisor { get; set; }
        public int idDeudor { get; set; }
    
        public virtual divisa divisa { get; set; }
        public virtual relacionclientefinanciera relacionclientefinanciera { get; set; }
        public virtual relacionclientefinanciera relacionclientefinanciera1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operacion> operacion { get; set; }
    }
}
