//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroFactorWS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public int idDireccion { get; set; }
        public string Calle { get; set; }
        public string NumeroExt { get; set; }
        public string NumeroInterior { get; set; }
        public int Persona_idPersona { get; set; }
        public int CodigoPostal_idCodigoPostal { get; set; }
        public int Colonia_idColonia { get; set; }
    
        public virtual codigopostal codigopostal { get; set; }
        public virtual colonia colonia { get; set; }
        public virtual persona persona { get; set; }
    }
}
