
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuroFactorWS.model
{

using System;
    using System.Collections.Generic;
    
public partial class financiera
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public financiera()
    {

        this.plancontratado = new HashSet<plancontratado>();

        this.relacionclientefinanciera = new HashSet<relacionclientefinanciera>();

        this.usuario = new HashSet<usuario>();

        this.deuda = new HashSet<deuda>();

    }


    public int idFinanciera { get; set; }

    public bool Regulada { get; set; }

    public int Persona_idPersona { get; set; }

    public bool Activa { get; set; }

    public string Correo { get; set; }



    public virtual persona persona { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<plancontratado> plancontratado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<relacionclientefinanciera> relacionclientefinanciera { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<usuario> usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<deuda> deuda { get; set; }

}

}
