//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuroFactorWS.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class planconsulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public planconsulta()
        {
            this.plancontratado = new HashSet<plancontratado>();
        }
    
        public int idPlanConsulta { get; set; }
        public string Nombre { get; set; }
        public int MaxConsultaMes { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Precio { get; set; }
        public bool Activo { get; set; }
        public bool Ilimitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plancontratado> plancontratado { get; set; }
    }
}
