
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BuroFactorWS.model
{

using System;
    using System.Collections.Generic;
    
public partial class relacionclientefinanciera
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public relacionclientefinanciera()
    {

        this.deuda = new HashSet<deuda>();

        this.deuda1 = new HashSet<deuda>();

    }


    public int idRelacionClienteFinanciera { get; set; }

    public string CorreoContacto { get; set; }

    public string Alias { get; set; }

    public int Financiera_idFinanciera { get; set; }

    public int Persona_idPersona { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<deuda> deuda { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<deuda> deuda1 { get; set; }

    public virtual financiera financiera { get; set; }

    public virtual persona persona { get; set; }

}

}
